url: https://p.t-baozi.cc
host: p.t-baozi.cc
siteType: NexusPHP
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAPoAAAD6AG1e1JrAAADO0lEQVR4nL1Ta0iTURg+aVYgJkIEFQmJoxAzRekCwZhNkLBZtokyMzKTqMTAqBRxaqmUtcpfQUYXiuVnZeEPay0KqT+RI6OgC6npTJxO3Le1fW7fOU+c6UztggX1wIFznvNeznnf5yXkP2IeISTEYDCECIIQyveT3D9J9FdYQAiJTEtLy9NqtWWEkBWEkIi/zR5mNBqvtbQIvVar1Wuz9dHWVmGwqeniY0LIklm2vwWvE8fC+vpTbxCAxy/7HH7Ai8ZG4xAhZNks218imHFxcXGJ0fLwvuh29jOXc4B5XINsxN5DzQ9uSxUVZdcJIctn+fyA4EVEZWVVm+gcBuCibnEQ45II6esIPC7OidQ37kJ1daV1WtCQGZF0Ol0oAE4u0Ggy2kTRCcDvl2UPKB0HZV5Q6gWjEiiVAFCf1yPiwIGCJu4PYB5fXF58kUmNcexsb2/nRaMydbPR0SEM2b+AQQKDFw6HHcPDg6DUzQAKi/meT6FQrJ/2yolfpqam5mVnZ5eq1WnW0dERABLlUXNycqFSqQAwBM9qtZq/ntvIYyPd0OdmlvMYSqVy/tSX9Xr9R8YoTKZbdMg+wIBxwDeGFtNVCC0COjqewmJ5hObmZgg3rwKSA4CPOh3vcaR0361p9Z945batW9NNphsfL5w/g4EvNgr4KWO8VhwM/f2f0Nv7HoA8yVBIHrs8bHuBzMz0a4vCwnYlxIQvndHc6OjIqNjYaH3b/ZtOXp/Ptn7a+bqLuzKA8Uiyz+9mL7teoafnHYP0Adcvn/UWFhYci1615hAhpCI8PCo+JiY5MtilQOvVqg2ac8aT3ZerNRBqNvot5tug0gAksRePzSZmKl/nv1KjQV191bstys0ZyUlJDVXlO152PjnxtqHucJdKmVw7pUMun8l91KXDcVb57kYUbI9/VlSYZ9BmZ9WW5K59jjspOL93dQcXf6D+mlX3+swZkDuLqONpPkrzYvtmaNJgmOhW+pZNSQd1Caez1BsUwbssdaJif9bahtTNiXFBrignKeVofvyeEm2c7njOyt1FmpiUH2dmxjgFBDs/mOjnNnOAgZAQQSChBN8dpzjD91ELcDoSGlz8/EeJ5oJvLAgBURWaOLcAAAAASUVORK5CYII=
asSource: false
asTarget: true
uploadPath: /upload.php
seedDomSelector: '#top~table:first>tbody>tr:nth-child(6)'
search:
  path: /torrents.php
  imdbOptionKey: '4'
  nameOptionKey: '0'
  params:
    incldead: '0'
    search_area: '{optionKey}'
    search: '{imdb}'
    sort: '5'
    type: desc
  result:
    list: '.torrents>tbody>tr'
    url: '.torrentname td a[href*="details.php?id="]'
    name: '.torrentname td a[href*="details.php?id="]'
    size: 'td:nth-child(5)'
name:
  selector: 'input[name="name"]'
subtitle:
  selector: 'input[name="small_descr"]'
description:
  selector: 'textarea[name="descr"]'
anonymous:
  selector: 'input[name="uplver"]'
torrent:
  selector: 'input[name="file"]'
category:
  selector: 'select[name="type"]'
  map:
    movie: '401'
    tv: '402'
    tvPack: '402'
    documentary: '404'
    concert: '406'
    sport: '407'
    cartoon: '405'
    variety: '403'
    music: '408'
    other: '409'
videoCodec:
  selector: 'select[name="codec_sel[4]"]'
  map:
    h264: '1'
    x264: '1'
    hevc: '6'
    x265: '6'
    h265: '6'
    mpeg2: '4'
    vc1: '2'
    # TODO: AV1 has no standard semantic key
audioCodec:
  selector: 'select[name="audiocodec_sel[4]"]'
  map:
    aac: '6'
    ac3: '1'
    dd: '1'
    dd+: '1'
    flac: '13'
    dts: '3'
    truehd: '11'
    lpcm: '12'
    dtshdma: '10'
    atmos: '9'
    dtsx: '8'
videoType:
  selector: 'select[name="medium_sel[4]"]'
  map:
    uhdbluray: '11'
    bluray: '1'
    remux: '3'
    encode: '7'
    web: '10'
    hdtv: '5'
    dvd: '6'
    dvdrip: '7'
    diy: '13'
    other: '4'
resolution:
  selector: 'select[name="standard_sel[4]"]'
  map:
    4320p: '6'
    2160p: '5'
    1080p: '1'
    1080i: '2'
    720p: '3'
    576p: '4'
    480p: '4'
team:
  selector: 'select[name="team_sel[4]"]'
  map:
    bzweb: '6'
    bzpt: '7'
    hds: '1'
    chd: '2'
    myisilu: '3'
    wiki: '4'
    other: '5'
