url: https://www.ptskit.org
host: www.ptskit.org
siteType: NexusPHP
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAErUlEQVR4nH2UeWwUdRTH39yzM7szO3vvdunWpTQtFIuttVQOExWpNkgEOaRNqokSQEBQKBCIjUWDRqAKyKERg9ISSoslHOEKRRMiEM8gghDLJchVAWuxdGfma7aXjaDfv97v98vv897M770v0b3FEBFPFWDvdXh/MKjmhcNKMgYRO46Io/8R2wXsUBGRFJAoTkTF/XLyF0aHjtqmBFK/zHOSr1fyu5Tc5ICKjooKC4MBPZxaLmUUVItDS77nxlS2xMursefYWXPmtlMgo+/emCZNGxHps/uxcHRnwKXPolhM7qEBPVkE8kRTiGggXzz3HLM+AdpgWcxGwLXJsmYeRyJz2nJzIFHLoUjMau7bD+25+eYH0TSQICzrXaHscBpTRo4ccKR8Vv9b08ucv+h9s3+ldbfAVMOkte02LWu2aeF36NMnBz9JMixf0LypGyYMT1ulqIAcjk96aEOGZNTs3DIaiaZUy7rgAi6LqF3BgskdA6Z4HmgDIExYCSJKzJGc1h3Dj3OGD/sUN06pHrOIl0CGNrGb51m5fFgz8CbMHymB05xtnuAsnJXwZAHdofBDN9hNADt2FWSZdm/V/c22J4DtLh3EMbfDvHDdxwt/SNFoehdvsGPxHOUkLok4tY+znn2Kx9GtPHBVxIKXKEHx4lauFmAnbYDg4Hdt1fwXbxt+nPH4sEBR2wxVrZO87pdR0fmgHSp9Rt2OMwxO7+csYqS29xaJCbRImFdKNqWPgtgAky3dAhKZzTM032FT9eKGN2D+5fPbjZqGXIfjU6qt/acXhxW43mk+yqHtOG/OeF6wT+7lbVyUUDSIbP3hSdDrYFLZDhiKszoUj5e9Jrtwzem1fzf8tuULmCucLpDqmtkDDEe9JUfqeaCJt9p+5oBrrH1gtQieqOWB0rk3x30FPFLRCOL0gx0XfMarA0TH9T0ON9q8IfOgZiBFkb6uaGzku5D+QTVVgoVzPFq/Ye2Gt1gr1SsmX3XFwlUfHzvcDHgLp0IUuCulOTlHx6ambSKvZ3Ol5AK8QeuA5kFRgL2kKEqoC5jpXVIunscVFsdqOEtleTjd/qpkpiVrN16d8MbnkIm1G7Ky0J7ZH+fDERxy6rhoeGF5AtYazYXJg7hLREqoZ0penCjvxwUONxo55MWkyxQrc+cThbInzm/1RbLQGArZMCL2dV4z77j8ZrIy6F7UkdtanCNg/hPOb4nWCVRb2+kUjw9XVt0+wQD7GLMwTQBRSk5sZEEaq7jNBk3Hn0rAfpt1mnPdsvmu7EysJ91cRGqiMptv3zlVRnqaMa/jY7utJxo2nptdzGN4BmMTL7RQLPhCrqps+UJ1oUnwWTM0yfyokMGHQ1ksHcLi/UcZ1JewVv0UGYOz1HqicWJvp+mK5F35xGMWp7SuEbS2H3gddYxmzokIiZphDMbHpMPEquPTfers0QPkHSOylTrF5Soj6t8N62F1dHkkM5Jxn0Nomq6LqPJJ9uspApbmMfbqwSwe9CaHf4R6VxGdJptc3+WLnaOjB9PiQcdnT/fjzr+Szfw2Pi4e0WStpNfFZK9xyRgVHXeSv+yeJtuduesw1SDyh4gmC8lVxb+c/L/0N8Dn45Zu4r0nAAAAAElFTkSuQmCC
asSource: false
asTarget: true
uploadPath: /upload.php
seedDomSelector: '#top~table:first>tbody>tr:nth-child(6)'
search:
  path: /torrents.php
  imdbOptionKey: '4'
  nameOptionKey: '0'
  params:
    incldead: '0'
    search_area: '{optionKey}'
    search: '{imdb}'
  result:
    list: '.torrents>tbody>tr'
    url: '.torrentname td a[href*="details.php?id="]'
    name: '.torrentname td a[href*="details.php?id="]'
    size: 'td:nth-child(5)'
name:
  selector: 'input[name="name"]'
subtitle:
  selector: 'input[name="small_descr"]'
description:
  selector: 'textarea[name="descr"]'
torrent:
  selector: 'input[name="file"]'
category:
  selector: 'select[name="type"]'
  map:
    movie: '404'
    tv: '405'
    tvPack: '405'
    variety: '409'
    music: '408'
    cartoon: '407'
    other: '406'
    # TODO: 短剧 (401) - short drama, 动态漫 (402) - motion comic, 游戏 (403) - game
