url: "https://www.yemapt.org"
host: www1?.yemapt.org
siteType: YemaPT
asSource: false
asTarget: true
uploadPath: /#/torrent/add
seedDomSelector: "form.ant-form"
needDoubanInfo: false
name:
  selector: "#showName"
subtitle:
  selector: "#shortDesc"
description:
  selector: "#longDesc"
torrent:
  selector: "#fileList"
imdb:
  selector: "#imdb"
douban:
  selector: "#douban"
poster: "#picture"
mediaInfo:
  selector: "#mediaInfo"
category:
  selector: "#categoryId"
  map:
    movie: "电影"
    tv: "剧集"
    tvPack: "剧集"
    cartoon: "动漫"
    documentary: "纪录片"
    variety: "综艺"
    sport: "体育"
    app: "软件"
    game: "游戏"
    ebook: "书籍"
    music: "音乐"
    concert: "MV/演唱会"
videoType:
  selector: "#medium"
  map:
    uhdbluray: "Blu-ray UHD (4K Complete)"
    bluray: "Blu-ray (1080p Complete)"
    remux: "Remux"
    encode: "Rip/Encode"
    hdtv: "HDTV/TV Cap"
    web: "Web-DL/WebRip"
    dvd: "DVD (Complete/ISO)"
    dvdrip: "DVDrip"
    music: "Audio CD/Vinyl"
videoCodec:
  selector: "#codec"
  map:
    h264: "H.264/AVC"
    x264: "H.264/AVC"
    hevc: "H.265/HEVC"
    h265: "H.265/HEVC"
    x265: "H.265/HEVC"
    vc1: "VC-1(Blu-ray)"
    xvid: "Xvid/DivX"
    divx: "Xvid/DivX"
    mpeg2: "MPEG-2(Blu-ray/DVD)"
    av1: "AV1"
    vp9: "VP9"
    vvc: "H.266/VVC"
audioCodec:
  selector: "#audiocodec"
  map:
    aac: "AAC"
    ac3: "AC3 (Dolby Digital)"
    dd: "AC3 (Dolby Digital)"
    dd+: "E-AC3 (Dolby Digital Plus)"
    flac: "FLAC"
    dts: "DTS"
    truehd: "TrueHD"
    lpcm: "LPCM"
    dtshdma: "DTS-HD MA"
    atmos: "TrueHD Atmos"
    dtsx: "DTS-HD MA"
    ape: "APE"
    wav: "Other"
    mp3: "MP3"
    ogg: "OGG"
    opus: "Opus"
resolution:
  selector: "#standard"
  map:
    4320p: "8K"
    2160p: "4K/2160p"
    1440p: "2K/1440p"
    1080p: "1080p"
    1080i: "1080i"
    720p: "720p"
    720i: "720i"
    576p: "SD"
    480p: "SD"
team:
  selector: "#team"
  map:
    ourbits: "OurBits"
    btshd: "BtsHD"
    btstv: "BtsTV"
    hdchina: "HDChina"
    cmct: "CMCT"
    hhweb: "HHWEB"
    frds: "FRDS"
    mteam: "MTeam"
    qhstudio: "QHstudio"
    ubits: "UBits"
    other: "Other"
